### ISSUE TITLE
Overall bugs i found so far

### ISSUE THREAD

**Issue by Muffinmaker99** [P-DennyGamingYT/KRNL-UI#1]
Ello its me Muffinmaker some issues:
1# 
![grafik](https://user-images.githubusercontent.com/84511041/137604042-f3ba0ba5-e68e-4ae6-988e-1bd82021bacd.png)
font pls to white because not rly good visible
2# Can you maybe add an injection indicator to the inject button maybe somthing like injecting and injected.
3# The injection dont work

**Comment by Muffinmaker99** [comment]
also the close button dont work it stays open in the backround 
![grafik](https://user-images.githubusercontent.com/84511041/137604139-36051f35-7195-4149-ab2c-a1e82576a79d.png)

**Comment by P-DennyGamingYT** [comment]
Sorry for late comment, I have fixed these issues in release version 1.0.3 which fixed the injection error as that was because you did not have SLinjector installed. SLinjector now auto installs when you download the UI. The colors in the menu strip were fixed almost immediately as I just thought it was my windows theme screwing up the colors.

Regards,
[YT]P-DennyGaming#0001
